print(10*('='), "Tabela de Multiplicação", 10*('='))
num = int(input("Digite um número:"))
print("1 X {} = {}".format(num, num*1))
print("2 X {} = {}".format(num, num*2))
print("3 X {} = {}".format(num, num*3))
print("4 X {} = {}".format(num, num*4))
print("5 X {} = {}".format(num, num*5))
print("6 X {} = {}".format(num, num*6))
print("7 X {} = {}".format(num, num*7))
print("8 X {} = {}".format(num, num*8))
print("9 X {} = {}".format(num, num*9))
print("10 X {} = {}".format(num, num*10))