nome = str(input("Nome completo:").strip())
nome = nome.split()
print("Muito prezer em te conhecer!")
print("Seu primeiro nome é {}".format(nome[0]))
print("Seu último nome é {}".format(nome[len(nome)-1]))
